### PR TITLE
Build documentation with Jupyter book

### LINKED ISSUE #1: Fix banners
- [ ] Mobile
- [ ] Resizing the window to make it small
- [ ] Favicon

All bring back the UCL banner: add a small Turing one.

### LINKED ISSUE #2: Fix notes LaTeX compiling
It breaks down both locally and on Travis, investigate. Also cf. https://github.com/UCL/rsd-engineeringcourse/issues/71

### LINKED ISSUE #25: Update/simplify the GitHub pages build process
Currently our build is slightly fragile and relies on older versions of some of the toolchain. We should try to rewrite this to use updated versions.

### PR DESCRIPTION
**Pull request by jemrobinson**
## Summary
- Switches build system to use [Jupyter Book](https://jupyterbook.org/)
- Switches CI from Travis to GitHub Actions
- Removes old build system
- Fixes some Markdown errors in notebooks
- Ran `black` over the codebase to make the style consistent (except the cells that are demonstrating different code styles!)
- Adds an `Edit on GitHub` button when viewing the HTML docs
- Marks some cells as `raises-exception` which allows `Run All Cells` to continue past them
- Builds HTML and PDF versions

## Screenshots
Screenshot 2021-08-05 at 17 34 46

Screenshot 2021-08-05 at 17 35 29

## Issues
Closes #1. Closes #2. Closes #25.

## Notes
- As a *lot* of notebook metadata is changed, I would recommend reviewing with `ReviewNB` or similar
- Take a look at [the documentation branch](https://github.com/alan-turing-institute/rsd-engineeringcourse/tree/testdocs) to see the most recent build from this branch

- Currently the GitHub Action is setup to run on this branch (rather than `master`) and to push to `testdocs` rather than `gh-pages` which should be changed before merging

### CODE REVIEW

**Comment by LouiseABowler** [comment]
The Jupyter Book version of these notes is looking great @jemrobinson! 🚀 

I've gone through the first chapter (0); the diffs in reviewnb look fine and the rendered output is as expected. I'll carry on with further chapters next week. Building locally with `build_docs.sh` worked smoothly too 👍 

I did notice a couple of edits to make in the text as I went along; I'll start a separate issue to track them as each chapter deserves a careful read-through rather than whatever bits we happen to notice while reviewing for formatting.

**Comment by jemrobinson** [comment]
Is that "good to merge" @LouiseABowler or do you want to check anything else/have me make any changes?

**Comment by jack89roberts** [comment]
I've had a quick look through, looks really nice in jupyter book!

- Adding setup & build instructions to the readme would be nice.
- Chapter 2 some things fail due to git setup/authentication, but this was also the case before. For the last course, we ran builds for that chapter with my GitHub account I think, but there was a risk of the token being exposed if anything failed during the build process. I'll make a separate issue about this.

**Comment by kasra-hosseini** [comment]
@jemrobinson The JB is looking great! I tested one of the notebooks on Binder (with no errors/issues). Should we review all the notebooks before merge? I am happy to test some of them this week.

**Pull request merged**
